# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/work_pls/work_pls.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==work_pls || ORIG_REF_NAME==work_pls} -quiet] -quiet

# IP: bd/work_pls/ip/work_pls_usp_rf_data_converter_0_0/work_pls_usp_rf_data_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==work_pls_usp_rf_data_converter_0_0 || ORIG_REF_NAME==work_pls_usp_rf_data_converter_0_0} -quiet] -quiet

# IP: bd/work_pls/ip/work_pls_zynq_ultra_ps_e_0_0/work_pls_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==work_pls_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==work_pls_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/work_pls/ip/work_pls_Receiver_0_0/work_pls_Receiver_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==work_pls_Receiver_0_0 || ORIG_REF_NAME==work_pls_Receiver_0_0} -quiet] -quiet

# IP: bd/work_pls/ip/work_pls_axi_fifo_mm_s_0/work_pls_axi_fifo_mm_s_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==work_pls_axi_fifo_mm_s_0 || ORIG_REF_NAME==work_pls_axi_fifo_mm_s_0} -quiet] -quiet

# IP: bd/work_pls/ip/work_pls_axis_subset_converter_0/work_pls_axis_subset_converter_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==work_pls_axis_subset_converter_0 || ORIG_REF_NAME==work_pls_axis_subset_converter_0} -quiet] -quiet

# IP: bd/work_pls/ip/work_pls_xbar_0/work_pls_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==work_pls_xbar_0 || ORIG_REF_NAME==work_pls_xbar_0} -quiet] -quiet

# IP: bd/work_pls/ip/work_pls_auto_pc_0/work_pls_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==work_pls_auto_pc_0 || ORIG_REF_NAME==work_pls_auto_pc_0} -quiet] -quiet

# IP: bd/work_pls/ip/work_pls_ps8_0_axi_periph_0/work_pls_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==work_pls_ps8_0_axi_periph_0 || ORIG_REF_NAME==work_pls_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/work_pls/ip/work_pls_rst_ps8_0_96M_0/work_pls_rst_ps8_0_96M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==work_pls_rst_ps8_0_96M_0 || ORIG_REF_NAME==work_pls_rst_ps8_0_96M_0} -quiet] -quiet

# IP: bd/work_pls/ip/work_pls_axi_dma_0/work_pls_axi_dma_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==work_pls_axi_dma_0 || ORIG_REF_NAME==work_pls_axi_dma_0} -quiet] -quiet

# IP: bd/work_pls/ip/work_pls_axi_smc_0/work_pls_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==work_pls_axi_smc_0 || ORIG_REF_NAME==work_pls_axi_smc_0} -quiet] -quiet

# IP: bd/work_pls/ip/work_pls_xlconstant_0_0/work_pls_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==work_pls_xlconstant_0_0 || ORIG_REF_NAME==work_pls_xlconstant_0_0} -quiet] -quiet

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/PYNQ_Receiver/PYNQ_Receiver.gen/sources_1/bd/work_pls/work_pls_ooc.xdc
