# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/PLEASE/PLEASE.srcs/sources_1/bd/PYNQ_Design/ip/PYNQ_Design_rst_ps8_0_96M_0/PYNQ_Design_rst_ps8_0_96M_0.xci
# IP: The module: 'PYNQ_Design_rst_ps8_0_96M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/PLEASE/PLEASE.gen/sources_1/bd/PYNQ_Design/ip/PYNQ_Design_rst_ps8_0_96M_0/PYNQ_Design_rst_ps8_0_96M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PYNQ_Design_rst_ps8_0_96M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/PLEASE/PLEASE.gen/sources_1/bd/PYNQ_Design/ip/PYNQ_Design_rst_ps8_0_96M_0/PYNQ_Design_rst_ps8_0_96M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PYNQ_Design_rst_ps8_0_96M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/PLEASE/PLEASE.gen/sources_1/bd/PYNQ_Design/ip/PYNQ_Design_rst_ps8_0_96M_0/PYNQ_Design_rst_ps8_0_96M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PYNQ_Design_rst_ps8_0_96M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/PLEASE/PLEASE.srcs/sources_1/bd/PYNQ_Design/ip/PYNQ_Design_rst_ps8_0_96M_0/PYNQ_Design_rst_ps8_0_96M_0.xci
# IP: The module: 'PYNQ_Design_rst_ps8_0_96M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/PLEASE/PLEASE.gen/sources_1/bd/PYNQ_Design/ip/PYNQ_Design_rst_ps8_0_96M_0/PYNQ_Design_rst_ps8_0_96M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PYNQ_Design_rst_ps8_0_96M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/PLEASE/PLEASE.gen/sources_1/bd/PYNQ_Design/ip/PYNQ_Design_rst_ps8_0_96M_0/PYNQ_Design_rst_ps8_0_96M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PYNQ_Design_rst_ps8_0_96M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/PLEASE/PLEASE.gen/sources_1/bd/PYNQ_Design/ip/PYNQ_Design_rst_ps8_0_96M_0/PYNQ_Design_rst_ps8_0_96M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PYNQ_Design_rst_ps8_0_96M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
