#!/bin/bash -f
#**********************************************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Script generated by Vivado on Tue Feb 25 14:29:36 +0000 2025
# SW Build 3865809 on Sun May  7 15:05:29 MDT 2023
#
# Tool Version Limit: 2023.05 
#
# Filename     : work_pls.sh
# Simulator    : Cadence Xcelium Parallel Simulator
# Description  : Simulation script generated by export_simulation Tcl command
# Purpose      : Run 'compile', 'elaborate', 'simulate' steps for compiling, elaborating and simulating the
#                design. The script will copy the library mapping file from the compiled library directory,
#                create design library directories and library mappings in the mapping file.
#
# Usage        : work_pls.sh
#                work_pls.sh [-lib_map_path] [-step] [-keep_index] [-noclean_files]*
#                work_pls.sh [-reset_run]
#                work_pls.sh [-reset_log]
#                work_pls.sh [-help]
#
#               * The -noclean_files switch is deprecated and will not peform any function (by default, the
#                 simulator generated files will not be removed unless -reset_run switch is used)
#
# Prerequisite : Before running export_simulation, you must first compile the Xilinx simulation library
#                using the 'compile_simlib' Tcl command (for more information, run 'compile_simlib -help'
#                command in the Vivado Tcl shell). After compiling the library, specify the -lib_map_path
#                switch with the directory path where the library is created while generating the script
#                with export_simulation.
#
#                Alternatively, you can set the library path by setting the following project property:-
#
#                 set_property compxlib.<simulator>_compiled_library_dir <path> [current_project]
#
#                You can also point to the simulation library by either setting the 'lib_map_path' global
#                variable in this script or specify it with the '-lib_map_path' switch while executing this
#                script (type 'work_pls.sh -help' for more information).
#
#                Note: For pure RTL based designs, the -lib_map_path switch can be specified later with the
#                generated script, but if design is targetted for system simulation containing SystemC/C++/C
#                sources, then the library path MUST be specified upfront when calling export_simulation.
#
#                For more information, refer 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#**********************************************************************************************************

# catch pipeline exit status
set -Eeuo pipefail

# set xmvhdl compile options
xmvhdl_opts="-64bit -messages -logfile .tmp_log -update"

# set xmvlog compile options
xmvlog_opts="-64bit -messages -logfile .tmp_log -update"

# set xmelab elaboration options
xmelab_opts="-64bit -relax -access +rwc -namemap_mixgen -messages -logfile elaborate.log"

# set xmsim simulation options
xmsim_opts="-64bit -logfile simulate.log"

# set design libraries for elaboration
design_libs_elab="-libname xilinx_vip -libname xpm -libname xil_defaultlib -libname axi_infrastructure_v1_1_0 -libname axi_vip_v1_1_14 -libname zynq_ultra_ps_e_vip_v1_0_14 -libname fifo_generator_v13_2_8 -libname xbip_utils_v3_0_10 -libname axi_utils_v2_0_6 -libname fir_compiler_v7_2_19 -libname xbip_pipe_v3_0_6 -libname xbip_bram18k_v3_0_6 -libname mult_gen_v12_0_18 -libname axi_lite_ipif_v3_0_4 -libname lib_pkg_v1_0_2 -libname lib_fifo_v1_0_17 -libname axi_fifo_mm_s_v4_3_0 -libname axis_infrastructure_v1_1_0 -libname axis_register_slice_v1_1_28 -libname axis_subset_converter_v1_1_28 -libname lib_cdc_v1_0_2 -libname proc_sys_reset_v5_0_13 -libname lib_srl_fifo_v1_0_2 -libname axi_datamover_v5_1_30 -libname axi_sg_v4_1_16 -libname axi_dma_v7_1_29 -libname xlconstant_v1_1_7 -libname smartconnect_v1_0 -libname axi_register_slice_v2_1_28 -libname generic_baseblocks_v2_1_0 -libname axi_data_fifo_v2_1_27 -libname axi_crossbar_v2_1_29 -libname axi_protocol_converter_v2_1_28 -libname xilinx_vip -libname unisims_ver -libname unimacro_ver -libname secureip"

# set design libraries
design_libs=(simprims_ver xilinx_vip xpm xil_defaultlib axi_infrastructure_v1_1_0 axi_vip_v1_1_14 zynq_ultra_ps_e_vip_v1_0_14 fifo_generator_v13_2_8 xbip_utils_v3_0_10 axi_utils_v2_0_6 fir_compiler_v7_2_19 xbip_pipe_v3_0_6 xbip_bram18k_v3_0_6 mult_gen_v12_0_18 axi_lite_ipif_v3_0_4 lib_pkg_v1_0_2 lib_fifo_v1_0_17 axi_fifo_mm_s_v4_3_0 axis_infrastructure_v1_1_0 axis_register_slice_v1_1_28 axis_subset_converter_v1_1_28 lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_30 axi_sg_v4_1_16 axi_dma_v7_1_29 xlconstant_v1_1_7 smartconnect_v1_0 axi_register_slice_v2_1_28 generic_baseblocks_v2_1_0 axi_data_fifo_v2_1_27 axi_crossbar_v2_1_29 axi_protocol_converter_v2_1_28)

# simulation root library directory
sim_lib_dir="xcelium_lib"

# script info
echo -e "work_pls.sh - Script generated by export_simulation (Vivado v2023.1 (64-bit)-id)\n"

# main steps
run()
{
  check_args $*
  setup
  if [[ ($b_step == 1) ]]; then
    case $step in
      "compile" )
       init_lib
       compile
      ;;
      "elaborate" )
       elaborate
      ;;
      "simulate" )
       simulate
      ;;
      * )
        echo -e "ERROR: Invalid or missing step '$step' (type \"./work_pls.sh -help\" for more information)\n"
        exit 1
      esac
  else
    init_lib
    compile
    elaborate
    simulate
  fi
}

# RUN_STEP: <compile>
compile()
{
  xmvlog -work xilinx_vip $xmvlog_opts -sv +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "D:/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
  "D:/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
  "D:/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
  "D:/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
  "D:/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
  "D:/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
  "D:/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
  "D:/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
  "D:/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee compile.log; cat .tmp_log > xmvlog.log 2>/dev/null

  xmvlog -work xpm $xmvlog_opts -sv +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "D:/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
  "D:/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
  "D:/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xpm $xmvhdl_opts \
  "D:/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log > xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/work_pls/ip/work_pls_usp_rf_data_converter_0_0/synth/work_pls_usp_rf_data_converter_0_0_block.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/work_pls/ip/work_pls_usp_rf_data_converter_0_0/synth/work_pls_usp_rf_data_converter_0_0_por_fsm_top.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/work_pls/ip/work_pls_usp_rf_data_converter_0_0/synth/work_pls_usp_rf_data_converter_0_0_bgt_fsm.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/work_pls/ip/work_pls_usp_rf_data_converter_0_0/synth/work_pls_usp_rf_data_converter_0_0_device_rom.sv" \
  "../../../bd/work_pls/ip/work_pls_usp_rf_data_converter_0_0/synth/work_pls_usp_rf_data_converter_0_0_por_fsm.sv" \
  "../../../bd/work_pls/ip/work_pls_usp_rf_data_converter_0_0/synth/work_pls_usp_rf_data_converter_0_0_por_fsm_disabled.sv" \
  "../../../bd/work_pls/ip/work_pls_usp_rf_data_converter_0_0/synth/work_pls_usp_rf_data_converter_0_0_tile_config.sv" \
  "../../../bd/work_pls/ip/work_pls_usp_rf_data_converter_0_0/synth/work_pls_usp_rf_data_converter_0_0_constants_config.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/work_pls/ip/work_pls_usp_rf_data_converter_0_0/synth/work_pls_usp_rf_data_converter_0_0_drp_arbiter.v" \
  "../../../bd/work_pls/ip/work_pls_usp_rf_data_converter_0_0/synth/work_pls_usp_rf_data_converter_0_0_drp_arbiter_adc.v" \
  "../../../bd/work_pls/ip/work_pls_usp_rf_data_converter_0_0/synth/work_pls_usp_rf_data_converter_0_0_register_decode.v" \
  "../../../bd/work_pls/ip/work_pls_usp_rf_data_converter_0_0/synth/work_pls_usp_rf_data_converter_0_0_address_decoder.v" \
  "../../../bd/work_pls/ip/work_pls_usp_rf_data_converter_0_0/synth/work_pls_usp_rf_data_converter_0_0_axi_lite_ipif.v" \
  "../../../bd/work_pls/ip/work_pls_usp_rf_data_converter_0_0/synth/work_pls_usp_rf_data_converter_0_0_counter_f.v" \
  "../../../bd/work_pls/ip/work_pls_usp_rf_data_converter_0_0/synth/work_pls_usp_rf_data_converter_0_0_pselect_f.v" \
  "../../../bd/work_pls/ip/work_pls_usp_rf_data_converter_0_0/synth/work_pls_usp_rf_data_converter_0_0_slave_attachment.v" \
  "../../../bd/work_pls/ip/work_pls_usp_rf_data_converter_0_0/synth/work_pls_usp_rf_data_converter_0_0_rf_wrapper.v" \
  "../../../bd/work_pls/ip/work_pls_usp_rf_data_converter_0_0/synth/work_pls_usp_rf_data_converter_0_0_drp_control_top.v" \
  "../../../bd/work_pls/ip/work_pls_usp_rf_data_converter_0_0/synth/work_pls_usp_rf_data_converter_0_0_drp_control.v" \
  "../../../bd/work_pls/ip/work_pls_usp_rf_data_converter_0_0/synth/work_pls_usp_rf_data_converter_0_0_drp_access_ctrl.v" \
  "../../../bd/work_pls/ip/work_pls_usp_rf_data_converter_0_0/synth/work_pls_usp_rf_data_converter_0_0_irq_req_ack.v" \
  "../../../bd/work_pls/ip/work_pls_usp_rf_data_converter_0_0/synth/work_pls_usp_rf_data_converter_0_0_irq_sync.v" \
  "../../../bd/work_pls/ip/work_pls_usp_rf_data_converter_0_0/synth/work_pls_usp_rf_data_converter_0_0bufg_gt_ctrl.v" \
  "../../../bd/work_pls/ip/work_pls_usp_rf_data_converter_0_0/synth/work_pls_usp_rf_data_converter_0_0_overvol_irq.v" \
  "../../../bd/work_pls/ip/work_pls_usp_rf_data_converter_0_0/synth/work_pls_usp_rf_data_converter_0_0_powerup_state_irq.v" \
  "../../../bd/work_pls/ip/work_pls_usp_rf_data_converter_0_0/synth/work_pls_usp_rf_data_converter_0_0_rst_cnt.v" \
  "../../../bd/work_pls/ip/work_pls_usp_rf_data_converter_0_0/synth/work_pls_usp_rf_data_converter_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_infrastructure_v1_1_0 $xmvlog_opts +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_vip_v1_1_14 $xmvlog_opts -sv +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ed63/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work zynq_ultra_ps_e_vip_v1_0_14 $xmvlog_opts -sv +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/work_pls/ip/work_pls_zynq_ultra_ps_e_0_0/sim/work_pls_zynq_ultra_ps_e_0_0_vip_wrapper.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work fifo_generator_v13_2_8 $xmvlog_opts +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ip/work_pls_Receiver_0_0/sin_wave_demodulate_fifo_generator_i0/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work fifo_generator_v13_2_8 $xmvhdl_opts \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ip/work_pls_Receiver_0_0/sin_wave_demodulate_fifo_generator_i0/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work fifo_generator_v13_2_8 $xmvlog_opts +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ip/work_pls_Receiver_0_0/sin_wave_demodulate_fifo_generator_i0/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/work_pls/ip/work_pls_Receiver_0_0/sin_wave_demodulate_fifo_generator_i0/sim/sin_wave_demodulate_fifo_generator_i0.v" \
  "../../../bd/work_pls/ip/work_pls_Receiver_0_0/sin_wave_demodulate_fifo_generator_i1/sim/sin_wave_demodulate_fifo_generator_i1.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xbip_utils_v3_0_10 $xmvhdl_opts \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ip/work_pls_Receiver_0_0/sin_wave_demodulate_fir_compiler_v7_2_i0/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_utils_v2_0_6 $xmvhdl_opts \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ip/work_pls_Receiver_0_0/sin_wave_demodulate_fir_compiler_v7_2_i0/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work fir_compiler_v7_2_19 $xmvhdl_opts \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ip/work_pls_Receiver_0_0/sin_wave_demodulate_fir_compiler_v7_2_i0/hdl/fir_compiler_v7_2_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/work_pls/ip/work_pls_Receiver_0_0/sin_wave_demodulate_fir_compiler_v7_2_i0/sim/sin_wave_demodulate_fir_compiler_v7_2_i0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xbip_pipe_v3_0_6 $xmvhdl_opts \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ip/work_pls_Receiver_0_0/sin_wave_demodulate_mult_gen_v12_0_i0/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xbip_bram18k_v3_0_6 $xmvhdl_opts \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ip/work_pls_Receiver_0_0/sin_wave_demodulate_mult_gen_v12_0_i0/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work mult_gen_v12_0_18 $xmvhdl_opts \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ip/work_pls_Receiver_0_0/sin_wave_demodulate_mult_gen_v12_0_i0/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/work_pls/ip/work_pls_Receiver_0_0/sin_wave_demodulate_mult_gen_v12_0_i0/sim/sin_wave_demodulate_mult_gen_v12_0_i0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V200X $xmvhdl_opts \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/0f0d/hdl/conv_pkg.vhd" \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/0f0d/hdl/synth_reg.vhd" \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/0f0d/hdl/synth_reg_w_init.vhd" \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/0f0d/hdl/srl17e.vhd" \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/0f0d/hdl/srl33e.vhd" \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/0f0d/hdl/synth_reg_reg.vhd" \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/0f0d/hdl/single_reg_w_init.vhd" \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/0f0d/hdl/xlclockdriver_rd.vhd" \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/0f0d/hdl/sin_wave_demodulate_entity_declarations.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/0f0d/hdl/sin_wave_demodulate.vhd" \
  "../../../bd/work_pls/ip/work_pls_Receiver_0_0/sim/work_pls_Receiver_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_lite_ipif_v3_0_4 $xmvhdl_opts \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lib_pkg_v1_0_2 $xmvhdl_opts \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lib_fifo_v1_0_17 $xmvhdl_opts \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/3d41/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_fifo_mm_s_v4_3_0 $xmvhdl_opts \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0c7/hdl/axi_fifo_mm_s_v4_3_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/work_pls/ip/work_pls_axi_fifo_mm_s_0/sim/work_pls_axi_fifo_mm_s_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work axis_infrastructure_v1_1_0 $xmvlog_opts +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axis_register_slice_v1_1_28 $xmvlog_opts +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/eb9f/hdl/axis_register_slice_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/work_pls/ip/work_pls_axis_subset_converter_0/hdl/tdata_work_pls_axis_subset_converter_0.v" \
  "../../../bd/work_pls/ip/work_pls_axis_subset_converter_0/hdl/tuser_work_pls_axis_subset_converter_0.v" \
  "../../../bd/work_pls/ip/work_pls_axis_subset_converter_0/hdl/tstrb_work_pls_axis_subset_converter_0.v" \
  "../../../bd/work_pls/ip/work_pls_axis_subset_converter_0/hdl/tkeep_work_pls_axis_subset_converter_0.v" \
  "../../../bd/work_pls/ip/work_pls_axis_subset_converter_0/hdl/tid_work_pls_axis_subset_converter_0.v" \
  "../../../bd/work_pls/ip/work_pls_axis_subset_converter_0/hdl/tdest_work_pls_axis_subset_converter_0.v" \
  "../../../bd/work_pls/ip/work_pls_axis_subset_converter_0/hdl/tlast_work_pls_axis_subset_converter_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axis_subset_converter_v1_1_28 $xmvlog_opts +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/d78a/hdl/axis_subset_converter_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/work_pls/ip/work_pls_axis_subset_converter_0/hdl/top_work_pls_axis_subset_converter_0.v" \
  "../../../bd/work_pls/ip/work_pls_axis_subset_converter_0/sim/work_pls_axis_subset_converter_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work lib_cdc_v1_0_2 $xmvhdl_opts \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work proc_sys_reset_v5_0_13 $xmvhdl_opts \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/work_pls/ip/work_pls_rst_ps8_0_96M_0/sim/work_pls_rst_ps8_0_96M_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lib_srl_fifo_v1_0_2 $xmvhdl_opts \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_datamover_v5_1_30 $xmvhdl_opts \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/e959/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_sg_v4_1_16 $xmvhdl_opts \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/85d0/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_dma_v7_1_29 $xmvhdl_opts \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/50c3/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/work_pls/ip/work_pls_axi_dma_0/sim/work_pls_axi_dma_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xlconstant_v1_1_7 $xmvlog_opts +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/b0f2/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/work_pls/ip/work_pls_axi_smc_0/bd_0/ip/ip_0/sim/bd_c659_one_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/work_pls/ip/work_pls_axi_smc_0/bd_0/ip/ip_1/sim/bd_c659_psr_aclk_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/c012/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/work_pls/ip/work_pls_axi_smc_0/bd_0/ip/ip_2/sim/bd_c659_arsw_0.sv" \
  "../../../bd/work_pls/ip/work_pls_axi_smc_0/bd_0/ip/ip_3/sim/bd_c659_rsw_0.sv" \
  "../../../bd/work_pls/ip/work_pls_axi_smc_0/bd_0/ip/ip_4/sim/bd_c659_awsw_0.sv" \
  "../../../bd/work_pls/ip/work_pls_axi_smc_0/bd_0/ip/ip_5/sim/bd_c659_wsw_0.sv" \
  "../../../bd/work_pls/ip/work_pls_axi_smc_0/bd_0/ip/ip_6/sim/bd_c659_bsw_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/be1f/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/work_pls/ip/work_pls_axi_smc_0/bd_0/ip/ip_7/sim/bd_c659_s00mmu_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/4fd2/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/work_pls/ip/work_pls_axi_smc_0/bd_0/ip/ip_8/sim/bd_c659_s00tr_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/637d/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/work_pls/ip/work_pls_axi_smc_0/bd_0/ip/ip_9/sim/bd_c659_s00sic_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f38e/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/work_pls/ip/work_pls_axi_smc_0/bd_0/ip/ip_10/sim/bd_c659_s00a2s_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/work_pls/ip/work_pls_axi_smc_0/bd_0/ip/ip_11/sim/bd_c659_sawn_0.sv" \
  "../../../bd/work_pls/ip/work_pls_axi_smc_0/bd_0/ip/ip_12/sim/bd_c659_swn_0.sv" \
  "../../../bd/work_pls/ip/work_pls_axi_smc_0/bd_0/ip/ip_13/sim/bd_c659_sbn_0.sv" \
  "../../../bd/work_pls/ip/work_pls_axi_smc_0/bd_0/ip/ip_14/sim/bd_c659_s01mmu_0.sv" \
  "../../../bd/work_pls/ip/work_pls_axi_smc_0/bd_0/ip/ip_15/sim/bd_c659_s01tr_0.sv" \
  "../../../bd/work_pls/ip/work_pls_axi_smc_0/bd_0/ip/ip_16/sim/bd_c659_s01sic_0.sv" \
  "../../../bd/work_pls/ip/work_pls_axi_smc_0/bd_0/ip/ip_17/sim/bd_c659_s01a2s_0.sv" \
  "../../../bd/work_pls/ip/work_pls_axi_smc_0/bd_0/ip/ip_18/sim/bd_c659_sarn_0.sv" \
  "../../../bd/work_pls/ip/work_pls_axi_smc_0/bd_0/ip/ip_19/sim/bd_c659_srn_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/9cc5/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/work_pls/ip/work_pls_axi_smc_0/bd_0/ip/ip_20/sim/bd_c659_m00s2a_0.sv" \
  "../../../bd/work_pls/ip/work_pls_axi_smc_0/bd_0/ip/ip_21/sim/bd_c659_m00arn_0.sv" \
  "../../../bd/work_pls/ip/work_pls_axi_smc_0/bd_0/ip/ip_22/sim/bd_c659_m00rn_0.sv" \
  "../../../bd/work_pls/ip/work_pls_axi_smc_0/bd_0/ip/ip_23/sim/bd_c659_m00awn_0.sv" \
  "../../../bd/work_pls/ip/work_pls_axi_smc_0/bd_0/ip/ip_24/sim/bd_c659_m00wn_0.sv" \
  "../../../bd/work_pls/ip/work_pls_axi_smc_0/bd_0/ip/ip_25/sim/bd_c659_m00bn_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/6bba/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/work_pls/ip/work_pls_axi_smc_0/bd_0/ip/ip_26/sim/bd_c659_m00e_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/work_pls/ip/work_pls_axi_smc_0/bd_0/sim/bd_c659.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_register_slice_v2_1_28 $xmvlog_opts +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/87d1/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/work_pls/ip/work_pls_axi_smc_0/sim/work_pls_axi_smc_0.v" \
  "../../../bd/work_pls/ip/work_pls_xlconstant_0_0/sim/work_pls_xlconstant_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work generic_baseblocks_v2_1_0 $xmvlog_opts +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_data_fifo_v2_1_27 $xmvlog_opts +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/fab7/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_crossbar_v2_1_29 $xmvlog_opts +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f8f3/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/work_pls/ip/work_pls_xbar_0/sim/work_pls_xbar_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib $xmvhdl_opts \
  "../../../bd/work_pls/sim/work_pls.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work axi_protocol_converter_v2_1_28 $xmvlog_opts +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8c02/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/ec67/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f805/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/8713/hdl" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/f0b6/hdl/verilog" +incdir+"../../../../PYNQ_Receiver_2023.gen/sources_1/bd/work_pls/ipshared/66be/hdl/verilog" +incdir+"D:/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/work_pls/ip/work_pls_auto_pc_0/sim/work_pls_auto_pc_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts \
  glbl.v \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null
}

# RUN_STEP: <elaborate>
elaborate()
{
  xmelab $xmelab_opts $design_libs_elab xil_defaultlib.work_pls xil_defaultlib.glbl
}

# RUN_STEP: <simulate>
simulate()
{
  xmsim $xmsim_opts xil_defaultlib.work_pls -input simulate.do
}

# STEP: setup
setup()
{
  # delete previous files for a clean rerun
  if [[ ($b_reset_run == 1) ]]; then
    reset_run
    echo -e "INFO: Simulation run files deleted.\n"
    exit 0
  fi

 # delete previous log files
  if [[ ($b_reset_log == 1) ]]; then
    reset_log
    echo -e "INFO: Simulation run log files deleted.\n"
    exit 0
  fi

  # add any setup/initialization commands here:-

  # <user specific commands>

}

# simulator index file/library directory processing
init_lib()
{
  if [[ ($b_keep_index == 1) ]]; then
    # keep previous design library mappings
    true
  else
    # define design library mappings
    create_lib_mappings
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # do not recreate design library directories
    true
  else
    # create design library directories
    create_lib_dir
  fi
}

# define design library mappings
create_lib_mappings()
{
  file="hdl.var"
  touch $file

  file="cds.lib"
  if [[ -e $file ]]; then
    if [[ ($lib_map_path == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file


  if [[ ($lib_map_path != "") ]]; then
    incl_ref="INCLUDE $lib_map_path/cds.lib"
    echo $incl_ref >> $file
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="DEFINE $lib $sim_lib_dir/$lib"
    echo $mapping >> $file
  done
}

# create design library directory
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi
  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# delete generated data from the previous run
reset_run()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log work_pls_sc.so .tmp_log xcelium_lib waves.shm c.obj)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# delete generated log files from the previous run
reset_log()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log .tmp_log)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# check switch argument value
check_arg_value()
{
  if [[ ($1 == "-step") && (($2 != "compile") && ($2 != "elaborate") && ($2 != "simulate")) ]];then
    echo -e "ERROR: Invalid or missing step '$2' (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($1 == "-lib_map_path") && ($2 == "") ]];then
    echo -e "ERROR: Simulation library directory path not specified (type \"./work_pls.sh -help\" for more information)\n"
    exit 1
  fi
}

# check command line arguments
check_args()
{
  arg_count=$#
  if [[ ("$#" == 1) && (("$1" == "-help") || ("$1" == "-h")) ]]; then
    usage
  fi
  while [[ "$#" -gt 0 ]]; do
    case $1 in
      -step)          check_arg_value $1 $2;step=$2;         b_step=1;         shift;;
      -lib_map_path)  check_arg_value $1 $2;lib_map_path=$2; b_lib_map_path=1; shift;;
      -gen_bypass)    b_gen_bypass=1    ;;
      -reset_run)     b_reset_run=1     ;;
      -reset_log)     b_reset_log=1     ;;
      -keep_index)    b_keep_index=1    ;;
      -noclean_files) b_noclean_files=1 ;;
      -help|-h)       ;;
      *) echo -e "ERROR: Invalid option specified '$1' (type "./top.sh -help" for more information)\n"; exit 1 ;;
    esac
     shift
  done

  # -reset_run is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_run == 1) ]]; then
    echo -e "ERROR: -reset_run switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -reset_log is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_log == 1) ]]; then
    echo -e "ERROR: -reset_log switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -keep_index is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_keep_index == 1) ]]; then
    echo -e "ERROR: -keep_index switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -noclean_files is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_noclean_files == 1) ]]; then
    echo -e "ERROR: -noclean_files switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi
}

# script usage
usage()
{
  msg="Usage: work_pls.sh [-help]\n\
Usage: work_pls.sh [-step]\n\
Usage: work_pls.sh [-lib_map_path]\n\
Usage: work_pls.sh [-reset_run]\n\
Usage: work_pls.sh [-reset_log]\n\
Usage: work_pls.sh [-keep_index]\n\
Usage: work_pls.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-step <name>] -- Execute specified step (simulate)\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Delete simulator generated data files from the previous run and recreate simulator setup\n\
file/library mappings for a clean run. This switch will not execute steps defined in the script.\n\n\
NOTE: To keep simulator index file settings from the previous run, use the -keep_index switch\n\
NOTE: To regenerate simulator index file but keep the simulator generated files, use the -noclean_files switch\n\n\
[-reset_log] -- Delete simulator generated log files from the previous run\n\n\
[-keep_index] -- Keep simulator index file settings from the previous run\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run\n"
  echo -e $msg
  exit 0
}

# initialize globals
step=""
lib_map_path=""
b_step=0
b_lib_map_path=0
b_gen_bypass=0
b_reset_run=0
b_reset_log=0
b_keep_index=0
b_noclean_files=0

# launch script
run $*
