# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/omg_please_work/omg_please_work.srcs/sources_1/bd/design_1/ip/design_1_Receiver_0_0/design_1_Receiver_0_0.xci
# IP: The module: 'design_1_Receiver_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/omg_please_work/omg_please_work.gen/sources_1/bd/design_1/ip/design_1_Receiver_0_0/sin_wave_demodulate_fifo_generator_i0/sin_wave_demodulate_fifo_generator_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sin_wave_demodulate_fifo_generator_i0 || ORIG_REF_NAME==sin_wave_demodulate_fifo_generator_i0} -quiet] -quiet

# IP: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/omg_please_work/omg_please_work.gen/sources_1/bd/design_1/ip/design_1_Receiver_0_0/sin_wave_demodulate_fifo_generator_i1/sin_wave_demodulate_fifo_generator_i1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sin_wave_demodulate_fifo_generator_i1 || ORIG_REF_NAME==sin_wave_demodulate_fifo_generator_i1} -quiet] -quiet

# IP: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/omg_please_work/omg_please_work.gen/sources_1/bd/design_1/ip/design_1_Receiver_0_0/sin_wave_demodulate_fir_compiler_v7_2_i0/sin_wave_demodulate_fir_compiler_v7_2_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sin_wave_demodulate_fir_compiler_v7_2_i0 || ORIG_REF_NAME==sin_wave_demodulate_fir_compiler_v7_2_i0} -quiet] -quiet

# IP: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/omg_please_work/omg_please_work.gen/sources_1/bd/design_1/ip/design_1_Receiver_0_0/sin_wave_demodulate_mult_gen_v12_0_i0/sin_wave_demodulate_mult_gen_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sin_wave_demodulate_mult_gen_v12_0_i0 || ORIG_REF_NAME==sin_wave_demodulate_mult_gen_v12_0_i0} -quiet] -quiet

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/omg_please_work/omg_please_work.gen/sources_1/bd/design_1/ip/design_1_Receiver_0_0/sin_wave_demodulate_fifo_generator_i0/sin_wave_demodulate_fifo_generator_i0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==sin_wave_demodulate_fifo_generator_i0 || ORIG_REF_NAME==sin_wave_demodulate_fifo_generator_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/omg_please_work/omg_please_work.gen/sources_1/bd/design_1/ip/design_1_Receiver_0_0/constrs/sin_wave_demodulate.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_Receiver_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/omg_please_work/omg_please_work.gen/sources_1/bd/design_1/ip/design_1_Receiver_0_0/sin_wave_demodulate_fifo_generator_i1/sin_wave_demodulate_fifo_generator_i1.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==sin_wave_demodulate_fifo_generator_i1 || ORIG_REF_NAME==sin_wave_demodulate_fifo_generator_i1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/omg_please_work/omg_please_work.gen/sources_1/bd/design_1/ip/design_1_Receiver_0_0/sin_wave_demodulate_fir_compiler_v7_2_i0/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==sin_wave_demodulate_fir_compiler_v7_2_i0 || ORIG_REF_NAME==sin_wave_demodulate_fir_compiler_v7_2_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/omg_please_work/omg_please_work.srcs/sources_1/bd/design_1/ip/design_1_Receiver_0_0/design_1_Receiver_0_0.xci
# IP: The module: 'design_1_Receiver_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/omg_please_work/omg_please_work.gen/sources_1/bd/design_1/ip/design_1_Receiver_0_0/sin_wave_demodulate_fifo_generator_i0/sin_wave_demodulate_fifo_generator_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sin_wave_demodulate_fifo_generator_i0 || ORIG_REF_NAME==sin_wave_demodulate_fifo_generator_i0} -quiet] -quiet

# IP: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/omg_please_work/omg_please_work.gen/sources_1/bd/design_1/ip/design_1_Receiver_0_0/sin_wave_demodulate_fifo_generator_i1/sin_wave_demodulate_fifo_generator_i1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sin_wave_demodulate_fifo_generator_i1 || ORIG_REF_NAME==sin_wave_demodulate_fifo_generator_i1} -quiet] -quiet

# IP: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/omg_please_work/omg_please_work.gen/sources_1/bd/design_1/ip/design_1_Receiver_0_0/sin_wave_demodulate_fir_compiler_v7_2_i0/sin_wave_demodulate_fir_compiler_v7_2_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sin_wave_demodulate_fir_compiler_v7_2_i0 || ORIG_REF_NAME==sin_wave_demodulate_fir_compiler_v7_2_i0} -quiet] -quiet

# IP: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/omg_please_work/omg_please_work.gen/sources_1/bd/design_1/ip/design_1_Receiver_0_0/sin_wave_demodulate_mult_gen_v12_0_i0/sin_wave_demodulate_mult_gen_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sin_wave_demodulate_mult_gen_v12_0_i0 || ORIG_REF_NAME==sin_wave_demodulate_mult_gen_v12_0_i0} -quiet] -quiet

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/omg_please_work/omg_please_work.gen/sources_1/bd/design_1/ip/design_1_Receiver_0_0/sin_wave_demodulate_fifo_generator_i0/sin_wave_demodulate_fifo_generator_i0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==sin_wave_demodulate_fifo_generator_i0 || ORIG_REF_NAME==sin_wave_demodulate_fifo_generator_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/omg_please_work/omg_please_work.gen/sources_1/bd/design_1/ip/design_1_Receiver_0_0/constrs/sin_wave_demodulate.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_Receiver_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/omg_please_work/omg_please_work.gen/sources_1/bd/design_1/ip/design_1_Receiver_0_0/sin_wave_demodulate_fifo_generator_i1/sin_wave_demodulate_fifo_generator_i1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==sin_wave_demodulate_fifo_generator_i1 || ORIG_REF_NAME==sin_wave_demodulate_fifo_generator_i1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/omg_please_work/omg_please_work.gen/sources_1/bd/design_1/ip/design_1_Receiver_0_0/sin_wave_demodulate_fir_compiler_v7_2_i0/constraints/fir_compiler_v7_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==sin_wave_demodulate_fir_compiler_v7_2_i0 || ORIG_REF_NAME==sin_wave_demodulate_fir_compiler_v7_2_i0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
