# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/helloworld/helloworld.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==helloworld || ORIG_REF_NAME==helloworld} -quiet] -quiet

# IP: bd/helloworld/ip/helloworld_zynq_ultra_ps_e_0_2/helloworld_zynq_ultra_ps_e_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==helloworld_zynq_ultra_ps_e_0_2 || ORIG_REF_NAME==helloworld_zynq_ultra_ps_e_0_2} -quiet] -quiet

# IP: bd/helloworld/ip/helloworld_usp_rf_data_converter_0_2/helloworld_usp_rf_data_converter_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==helloworld_usp_rf_data_converter_0_2 || ORIG_REF_NAME==helloworld_usp_rf_data_converter_0_2} -quiet] -quiet

# IP: bd/helloworld/ip/helloworld_xlconstant_0_0/helloworld_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==helloworld_xlconstant_0_0 || ORIG_REF_NAME==helloworld_xlconstant_0_0} -quiet] -quiet

# IP: bd/helloworld/ip/helloworld_Data_generation_0_0/helloworld_Data_generation_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==helloworld_Data_generation_0_0 || ORIG_REF_NAME==helloworld_Data_generation_0_0} -quiet] -quiet

# IP: bd/helloworld/ip/helloworld_Receiver_0_2/helloworld_Receiver_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==helloworld_Receiver_0_2 || ORIG_REF_NAME==helloworld_Receiver_0_2} -quiet] -quiet

# IP: bd/helloworld/ip/helloworld_axi_dma_5/helloworld_axi_dma_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==helloworld_axi_dma_5 || ORIG_REF_NAME==helloworld_axi_dma_5} -quiet] -quiet

# IP: bd/helloworld/ip/helloworld_axi_smc_5/helloworld_axi_smc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==helloworld_axi_smc_5 || ORIG_REF_NAME==helloworld_axi_smc_5} -quiet] -quiet

# IP: bd/helloworld/ip/helloworld_rst_ps8_0_96M_4/helloworld_rst_ps8_0_96M_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==helloworld_rst_ps8_0_96M_4 || ORIG_REF_NAME==helloworld_rst_ps8_0_96M_4} -quiet] -quiet

# IP: bd/helloworld/ip/helloworld_axi_fifo_mm_s_5/helloworld_axi_fifo_mm_s_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==helloworld_axi_fifo_mm_s_5 || ORIG_REF_NAME==helloworld_axi_fifo_mm_s_5} -quiet] -quiet

# IP: bd/helloworld/ip/helloworld_xbar_2/helloworld_xbar_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==helloworld_xbar_2 || ORIG_REF_NAME==helloworld_xbar_2} -quiet] -quiet

# IP: bd/helloworld/ip/helloworld_ps8_0_axi_periph_3/helloworld_ps8_0_axi_periph_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==helloworld_ps8_0_axi_periph_3 || ORIG_REF_NAME==helloworld_ps8_0_axi_periph_3} -quiet] -quiet

# IP: bd/helloworld/ip/helloworld_auto_ds_0/helloworld_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==helloworld_auto_ds_0 || ORIG_REF_NAME==helloworld_auto_ds_0} -quiet] -quiet

# IP: bd/helloworld/ip/helloworld_auto_pc_0/helloworld_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==helloworld_auto_pc_0 || ORIG_REF_NAME==helloworld_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/helloworld_ooc.xdc
