# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.srcs/sources_1/bd/helloworld/ip/helloworld_auto_ds_0/helloworld_auto_ds_0.xci
# IP: The module: 'helloworld_auto_ds_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_auto_ds_0/helloworld_auto_ds_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'helloworld_auto_ds_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_auto_ds_0/helloworld_auto_ds_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'helloworld_auto_ds_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.srcs/sources_1/bd/helloworld/ip/helloworld_auto_ds_0/helloworld_auto_ds_0.xci
# IP: The module: 'helloworld_auto_ds_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_auto_ds_0/helloworld_auto_ds_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'helloworld_auto_ds_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_auto_ds_0/helloworld_auto_ds_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'helloworld_auto_ds_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
