-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2024.1 (win64) Build 5076996 Wed May 22 18:37:14 MDT 2024
-- Date        : Tue Feb 25 12:36:25 2025
-- Host        : EEE-R446-25 running 64-bit major release  (build 9200)
-- Command     : write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix
--               decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ work_pls_axis_subset_converter_0_sim_netlist.vhdl
-- Design      : work_pls_axis_subset_converter_0
-- Purpose     : This VHDL netlist is a functional simulation representation of the design and should not be modified or
--               synthesized. This netlist cannot be used for SDF annotated simulation.
-- Device      : xczu28dr-ffvg1517-2-e
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
library UNISIM;
use UNISIM.VCOMPONENTS.ALL;
entity decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_top_work_pls_axis_subset_converter_0 is
  port (
    aclk : in STD_LOGIC;
    aresetn : in STD_LOGIC;
    aclken : in STD_LOGIC;
    s_axis_tvalid : in STD_LOGIC;
    s_axis_tready : out STD_LOGIC;
    s_axis_tdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axis_tstrb : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axis_tkeep : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axis_tlast : in STD_LOGIC;
    s_axis_tid : in STD_LOGIC_VECTOR ( 0 to 0 );
    s_axis_tdest : in STD_LOGIC_VECTOR ( 0 to 0 );
    s_axis_tuser : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axis_tvalid : out STD_LOGIC;
    m_axis_tready : in STD_LOGIC;
    m_axis_tdata : out STD_LOGIC_VECTOR ( 255 downto 0 );
    m_axis_tstrb : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axis_tkeep : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axis_tlast : out STD_LOGIC;
    m_axis_tid : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axis_tdest : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axis_tuser : out STD_LOGIC_VECTOR ( 0 to 0 );
    transfer_dropped : out STD_LOGIC;
    sparse_tkeep_removed : out STD_LOGIC
  );
  attribute C_DEFAULT_TLAST : integer;
  attribute C_DEFAULT_TLAST of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_top_work_pls_axis_subset_converter_0 : entity is 0;
  attribute C_FAMILY : string;
  attribute C_FAMILY of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_top_work_pls_axis_subset_converter_0 : entity is "zynquplus";
  attribute C_M_AXIS_SIGNAL_SET : integer;
  attribute C_M_AXIS_SIGNAL_SET of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_top_work_pls_axis_subset_converter_0 : entity is 19;
  attribute C_M_AXIS_TDATA_WIDTH : integer;
  attribute C_M_AXIS_TDATA_WIDTH of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_top_work_pls_axis_subset_converter_0 : entity is 256;
  attribute C_M_AXIS_TDEST_WIDTH : integer;
  attribute C_M_AXIS_TDEST_WIDTH of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_top_work_pls_axis_subset_converter_0 : entity is 1;
  attribute C_M_AXIS_TID_WIDTH : integer;
  attribute C_M_AXIS_TID_WIDTH of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_top_work_pls_axis_subset_converter_0 : entity is 1;
  attribute C_M_AXIS_TUSER_WIDTH : integer;
  attribute C_M_AXIS_TUSER_WIDTH of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_top_work_pls_axis_subset_converter_0 : entity is 1;
  attribute C_S_AXIS_SIGNAL_SET : integer;
  attribute C_S_AXIS_SIGNAL_SET of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_top_work_pls_axis_subset_converter_0 : entity is 19;
  attribute C_S_AXIS_TDATA_WIDTH : integer;
  attribute C_S_AXIS_TDATA_WIDTH of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_top_work_pls_axis_subset_converter_0 : entity is 32;
  attribute C_S_AXIS_TDEST_WIDTH : integer;
  attribute C_S_AXIS_TDEST_WIDTH of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_top_work_pls_axis_subset_converter_0 : entity is 1;
  attribute C_S_AXIS_TID_WIDTH : integer;
  attribute C_S_AXIS_TID_WIDTH of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_top_work_pls_axis_subset_converter_0 : entity is 1;
  attribute C_S_AXIS_TUSER_WIDTH : integer;
  attribute C_S_AXIS_TUSER_WIDTH of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_top_work_pls_axis_subset_converter_0 : entity is 1;
  attribute G_INDX_SS_TDATA : integer;
  attribute G_INDX_SS_TDATA of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_top_work_pls_axis_subset_converter_0 : entity is 1;
  attribute G_INDX_SS_TDEST : integer;
  attribute G_INDX_SS_TDEST of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_top_work_pls_axis_subset_converter_0 : entity is 6;
  attribute G_INDX_SS_TID : integer;
  attribute G_INDX_SS_TID of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_top_work_pls_axis_subset_converter_0 : entity is 5;
  attribute G_INDX_SS_TKEEP : integer;
  attribute G_INDX_SS_TKEEP of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_top_work_pls_axis_subset_converter_0 : entity is 3;
  attribute G_INDX_SS_TLAST : integer;
  attribute G_INDX_SS_TLAST of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_top_work_pls_axis_subset_converter_0 : entity is 4;
  attribute G_INDX_SS_TREADY : integer;
  attribute G_INDX_SS_TREADY of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_top_work_pls_axis_subset_converter_0 : entity is 0;
  attribute G_INDX_SS_TSTRB : integer;
  attribute G_INDX_SS_TSTRB of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_top_work_pls_axis_subset_converter_0 : entity is 2;
  attribute G_INDX_SS_TUSER : integer;
  attribute G_INDX_SS_TUSER of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_top_work_pls_axis_subset_converter_0 : entity is 7;
  attribute G_MASK_SS_TDATA : integer;
  attribute G_MASK_SS_TDATA of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_top_work_pls_axis_subset_converter_0 : entity is 2;
  attribute G_MASK_SS_TDEST : integer;
  attribute G_MASK_SS_TDEST of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_top_work_pls_axis_subset_converter_0 : entity is 64;
  attribute G_MASK_SS_TID : integer;
  attribute G_MASK_SS_TID of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_top_work_pls_axis_subset_converter_0 : entity is 32;
  attribute G_MASK_SS_TKEEP : integer;
  attribute G_MASK_SS_TKEEP of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_top_work_pls_axis_subset_converter_0 : entity is 8;
  attribute G_MASK_SS_TLAST : integer;
  attribute G_MASK_SS_TLAST of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_top_work_pls_axis_subset_converter_0 : entity is 16;
  attribute G_MASK_SS_TREADY : integer;
  attribute G_MASK_SS_TREADY of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_top_work_pls_axis_subset_converter_0 : entity is 1;
  attribute G_MASK_SS_TSTRB : integer;
  attribute G_MASK_SS_TSTRB of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_top_work_pls_axis_subset_converter_0 : entity is 4;
  attribute G_MASK_SS_TUSER : integer;
  attribute G_MASK_SS_TUSER of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_top_work_pls_axis_subset_converter_0 : entity is 128;
  attribute G_TASK_SEVERITY_ERR : integer;
  attribute G_TASK_SEVERITY_ERR of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_top_work_pls_axis_subset_converter_0 : entity is 2;
  attribute G_TASK_SEVERITY_INFO : integer;
  attribute G_TASK_SEVERITY_INFO of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_top_work_pls_axis_subset_converter_0 : entity is 0;
  attribute G_TASK_SEVERITY_WARNING : integer;
  attribute G_TASK_SEVERITY_WARNING of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_top_work_pls_axis_subset_converter_0 : entity is 1;
end decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_top_work_pls_axis_subset_converter_0;

architecture STRUCTURE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_top_work_pls_axis_subset_converter_0 is
  signal \<const0>\ : STD_LOGIC;
  signal \^m_axis_tready\ : STD_LOGIC;
  signal \^s_axis_tdata\ : STD_LOGIC_VECTOR ( 31 downto 0 );
  signal \^s_axis_tlast\ : STD_LOGIC;
  signal \^s_axis_tvalid\ : STD_LOGIC;
begin
  \^m_axis_tready\ <= m_axis_tready;
  \^s_axis_tdata\(31 downto 0) <= s_axis_tdata(31 downto 0);
  \^s_axis_tlast\ <= s_axis_tlast;
  \^s_axis_tvalid\ <= s_axis_tvalid;
  m_axis_tdata(255) <= \<const0>\;
  m_axis_tdata(254) <= \<const0>\;
  m_axis_tdata(253) <= \<const0>\;
  m_axis_tdata(252) <= \<const0>\;
  m_axis_tdata(251) <= \<const0>\;
  m_axis_tdata(250) <= \<const0>\;
  m_axis_tdata(249) <= \<const0>\;
  m_axis_tdata(248) <= \<const0>\;
  m_axis_tdata(247) <= \<const0>\;
  m_axis_tdata(246) <= \<const0>\;
  m_axis_tdata(245) <= \<const0>\;
  m_axis_tdata(244) <= \<const0>\;
  m_axis_tdata(243) <= \<const0>\;
  m_axis_tdata(242) <= \<const0>\;
  m_axis_tdata(241) <= \<const0>\;
  m_axis_tdata(240) <= \<const0>\;
  m_axis_tdata(239) <= \<const0>\;
  m_axis_tdata(238) <= \<const0>\;
  m_axis_tdata(237) <= \<const0>\;
  m_axis_tdata(236) <= \<const0>\;
  m_axis_tdata(235) <= \<const0>\;
  m_axis_tdata(234) <= \<const0>\;
  m_axis_tdata(233) <= \<const0>\;
  m_axis_tdata(232) <= \<const0>\;
  m_axis_tdata(231) <= \<const0>\;
  m_axis_tdata(230) <= \<const0>\;
  m_axis_tdata(229) <= \<const0>\;
  m_axis_tdata(228) <= \<const0>\;
  m_axis_tdata(227) <= \<const0>\;
  m_axis_tdata(226) <= \<const0>\;
  m_axis_tdata(225) <= \<const0>\;
  m_axis_tdata(224) <= \<const0>\;
  m_axis_tdata(223) <= \<const0>\;
  m_axis_tdata(222) <= \<const0>\;
  m_axis_tdata(221) <= \<const0>\;
  m_axis_tdata(220) <= \<const0>\;
  m_axis_tdata(219) <= \<const0>\;
  m_axis_tdata(218) <= \<const0>\;
  m_axis_tdata(217) <= \<const0>\;
  m_axis_tdata(216) <= \<const0>\;
  m_axis_tdata(215) <= \<const0>\;
  m_axis_tdata(214) <= \<const0>\;
  m_axis_tdata(213) <= \<const0>\;
  m_axis_tdata(212) <= \<const0>\;
  m_axis_tdata(211) <= \<const0>\;
  m_axis_tdata(210) <= \<const0>\;
  m_axis_tdata(209) <= \<const0>\;
  m_axis_tdata(208) <= \<const0>\;
  m_axis_tdata(207) <= \<const0>\;
  m_axis_tdata(206) <= \<const0>\;
  m_axis_tdata(205) <= \<const0>\;
  m_axis_tdata(204) <= \<const0>\;
  m_axis_tdata(203) <= \<const0>\;
  m_axis_tdata(202) <= \<const0>\;
  m_axis_tdata(201) <= \<const0>\;
  m_axis_tdata(200) <= \<const0>\;
  m_axis_tdata(199) <= \<const0>\;
  m_axis_tdata(198) <= \<const0>\;
  m_axis_tdata(197) <= \<const0>\;
  m_axis_tdata(196) <= \<const0>\;
  m_axis_tdata(195) <= \<const0>\;
  m_axis_tdata(194) <= \<const0>\;
  m_axis_tdata(193) <= \<const0>\;
  m_axis_tdata(192) <= \<const0>\;
  m_axis_tdata(191) <= \<const0>\;
  m_axis_tdata(190) <= \<const0>\;
  m_axis_tdata(189) <= \<const0>\;
  m_axis_tdata(188) <= \<const0>\;
  m_axis_tdata(187) <= \<const0>\;
  m_axis_tdata(186) <= \<const0>\;
  m_axis_tdata(185) <= \<const0>\;
  m_axis_tdata(184) <= \<const0>\;
  m_axis_tdata(183) <= \<const0>\;
  m_axis_tdata(182) <= \<const0>\;
  m_axis_tdata(181) <= \<const0>\;
  m_axis_tdata(180) <= \<const0>\;
  m_axis_tdata(179) <= \<const0>\;
  m_axis_tdata(178) <= \<const0>\;
  m_axis_tdata(177) <= \<const0>\;
  m_axis_tdata(176) <= \<const0>\;
  m_axis_tdata(175) <= \<const0>\;
  m_axis_tdata(174) <= \<const0>\;
  m_axis_tdata(173) <= \<const0>\;
  m_axis_tdata(172) <= \<const0>\;
  m_axis_tdata(171) <= \<const0>\;
  m_axis_tdata(170) <= \<const0>\;
  m_axis_tdata(169) <= \<const0>\;
  m_axis_tdata(168) <= \<const0>\;
  m_axis_tdata(167) <= \<const0>\;
  m_axis_tdata(166) <= \<const0>\;
  m_axis_tdata(165) <= \<const0>\;
  m_axis_tdata(164) <= \<const0>\;
  m_axis_tdata(163) <= \<const0>\;
  m_axis_tdata(162) <= \<const0>\;
  m_axis_tdata(161) <= \<const0>\;
  m_axis_tdata(160) <= \<const0>\;
  m_axis_tdata(159) <= \<const0>\;
  m_axis_tdata(158) <= \<const0>\;
  m_axis_tdata(157) <= \<const0>\;
  m_axis_tdata(156) <= \<const0>\;
  m_axis_tdata(155) <= \<const0>\;
  m_axis_tdata(154) <= \<const0>\;
  m_axis_tdata(153) <= \<const0>\;
  m_axis_tdata(152) <= \<const0>\;
  m_axis_tdata(151) <= \<const0>\;
  m_axis_tdata(150) <= \<const0>\;
  m_axis_tdata(149) <= \<const0>\;
  m_axis_tdata(148) <= \<const0>\;
  m_axis_tdata(147) <= \<const0>\;
  m_axis_tdata(146) <= \<const0>\;
  m_axis_tdata(145) <= \<const0>\;
  m_axis_tdata(144) <= \<const0>\;
  m_axis_tdata(143) <= \<const0>\;
  m_axis_tdata(142) <= \<const0>\;
  m_axis_tdata(141) <= \<const0>\;
  m_axis_tdata(140) <= \<const0>\;
  m_axis_tdata(139) <= \<const0>\;
  m_axis_tdata(138) <= \<const0>\;
  m_axis_tdata(137) <= \<const0>\;
  m_axis_tdata(136) <= \<const0>\;
  m_axis_tdata(135) <= \<const0>\;
  m_axis_tdata(134) <= \<const0>\;
  m_axis_tdata(133) <= \<const0>\;
  m_axis_tdata(132) <= \<const0>\;
  m_axis_tdata(131) <= \<const0>\;
  m_axis_tdata(130) <= \<const0>\;
  m_axis_tdata(129) <= \<const0>\;
  m_axis_tdata(128) <= \<const0>\;
  m_axis_tdata(127) <= \<const0>\;
  m_axis_tdata(126) <= \<const0>\;
  m_axis_tdata(125) <= \<const0>\;
  m_axis_tdata(124) <= \<const0>\;
  m_axis_tdata(123) <= \<const0>\;
  m_axis_tdata(122) <= \<const0>\;
  m_axis_tdata(121) <= \<const0>\;
  m_axis_tdata(120) <= \<const0>\;
  m_axis_tdata(119) <= \<const0>\;
  m_axis_tdata(118) <= \<const0>\;
  m_axis_tdata(117) <= \<const0>\;
  m_axis_tdata(116) <= \<const0>\;
  m_axis_tdata(115) <= \<const0>\;
  m_axis_tdata(114) <= \<const0>\;
  m_axis_tdata(113) <= \<const0>\;
  m_axis_tdata(112) <= \<const0>\;
  m_axis_tdata(111) <= \<const0>\;
  m_axis_tdata(110) <= \<const0>\;
  m_axis_tdata(109) <= \<const0>\;
  m_axis_tdata(108) <= \<const0>\;
  m_axis_tdata(107) <= \<const0>\;
  m_axis_tdata(106) <= \<const0>\;
  m_axis_tdata(105) <= \<const0>\;
  m_axis_tdata(104) <= \<const0>\;
  m_axis_tdata(103) <= \<const0>\;
  m_axis_tdata(102) <= \<const0>\;
  m_axis_tdata(101) <= \<const0>\;
  m_axis_tdata(100) <= \<const0>\;
  m_axis_tdata(99) <= \<const0>\;
  m_axis_tdata(98) <= \<const0>\;
  m_axis_tdata(97) <= \<const0>\;
  m_axis_tdata(96) <= \<const0>\;
  m_axis_tdata(95) <= \<const0>\;
  m_axis_tdata(94) <= \<const0>\;
  m_axis_tdata(93) <= \<const0>\;
  m_axis_tdata(92) <= \<const0>\;
  m_axis_tdata(91) <= \<const0>\;
  m_axis_tdata(90) <= \<const0>\;
  m_axis_tdata(89) <= \<const0>\;
  m_axis_tdata(88) <= \<const0>\;
  m_axis_tdata(87) <= \<const0>\;
  m_axis_tdata(86) <= \<const0>\;
  m_axis_tdata(85) <= \<const0>\;
  m_axis_tdata(84) <= \<const0>\;
  m_axis_tdata(83) <= \<const0>\;
  m_axis_tdata(82) <= \<const0>\;
  m_axis_tdata(81) <= \<const0>\;
  m_axis_tdata(80) <= \<const0>\;
  m_axis_tdata(79) <= \<const0>\;
  m_axis_tdata(78) <= \<const0>\;
  m_axis_tdata(77) <= \<const0>\;
  m_axis_tdata(76) <= \<const0>\;
  m_axis_tdata(75) <= \<const0>\;
  m_axis_tdata(74) <= \<const0>\;
  m_axis_tdata(73) <= \<const0>\;
  m_axis_tdata(72) <= \<const0>\;
  m_axis_tdata(71) <= \<const0>\;
  m_axis_tdata(70) <= \<const0>\;
  m_axis_tdata(69) <= \<const0>\;
  m_axis_tdata(68) <= \<const0>\;
  m_axis_tdata(67) <= \<const0>\;
  m_axis_tdata(66) <= \<const0>\;
  m_axis_tdata(65) <= \<const0>\;
  m_axis_tdata(64) <= \<const0>\;
  m_axis_tdata(63) <= \<const0>\;
  m_axis_tdata(62) <= \<const0>\;
  m_axis_tdata(61) <= \<const0>\;
  m_axis_tdata(60) <= \<const0>\;
  m_axis_tdata(59) <= \<const0>\;
  m_axis_tdata(58) <= \<const0>\;
  m_axis_tdata(57) <= \<const0>\;
  m_axis_tdata(56) <= \<const0>\;
  m_axis_tdata(55) <= \<const0>\;
  m_axis_tdata(54) <= \<const0>\;
  m_axis_tdata(53) <= \<const0>\;
  m_axis_tdata(52) <= \<const0>\;
  m_axis_tdata(51) <= \<const0>\;
  m_axis_tdata(50) <= \<const0>\;
  m_axis_tdata(49) <= \<const0>\;
  m_axis_tdata(48) <= \<const0>\;
  m_axis_tdata(47) <= \<const0>\;
  m_axis_tdata(46) <= \<const0>\;
  m_axis_tdata(45) <= \<const0>\;
  m_axis_tdata(44) <= \<const0>\;
  m_axis_tdata(43) <= \<const0>\;
  m_axis_tdata(42) <= \<const0>\;
  m_axis_tdata(41) <= \<const0>\;
  m_axis_tdata(40) <= \<const0>\;
  m_axis_tdata(39) <= \<const0>\;
  m_axis_tdata(38) <= \<const0>\;
  m_axis_tdata(37) <= \<const0>\;
  m_axis_tdata(36) <= \<const0>\;
  m_axis_tdata(35) <= \<const0>\;
  m_axis_tdata(34) <= \<const0>\;
  m_axis_tdata(33) <= \<const0>\;
  m_axis_tdata(32) <= \<const0>\;
  m_axis_tdata(31 downto 0) <= \^s_axis_tdata\(31 downto 0);
  m_axis_tdest(0) <= \<const0>\;
  m_axis_tid(0) <= \<const0>\;
  m_axis_tkeep(31) <= \<const0>\;
  m_axis_tkeep(30) <= \<const0>\;
  m_axis_tkeep(29) <= \<const0>\;
  m_axis_tkeep(28) <= \<const0>\;
  m_axis_tkeep(27) <= \<const0>\;
  m_axis_tkeep(26) <= \<const0>\;
  m_axis_tkeep(25) <= \<const0>\;
  m_axis_tkeep(24) <= \<const0>\;
  m_axis_tkeep(23) <= \<const0>\;
  m_axis_tkeep(22) <= \<const0>\;
  m_axis_tkeep(21) <= \<const0>\;
  m_axis_tkeep(20) <= \<const0>\;
  m_axis_tkeep(19) <= \<const0>\;
  m_axis_tkeep(18) <= \<const0>\;
  m_axis_tkeep(17) <= \<const0>\;
  m_axis_tkeep(16) <= \<const0>\;
  m_axis_tkeep(15) <= \<const0>\;
  m_axis_tkeep(14) <= \<const0>\;
  m_axis_tkeep(13) <= \<const0>\;
  m_axis_tkeep(12) <= \<const0>\;
  m_axis_tkeep(11) <= \<const0>\;
  m_axis_tkeep(10) <= \<const0>\;
  m_axis_tkeep(9) <= \<const0>\;
  m_axis_tkeep(8) <= \<const0>\;
  m_axis_tkeep(7) <= \<const0>\;
  m_axis_tkeep(6) <= \<const0>\;
  m_axis_tkeep(5) <= \<const0>\;
  m_axis_tkeep(4) <= \<const0>\;
  m_axis_tkeep(3) <= \<const0>\;
  m_axis_tkeep(2) <= \<const0>\;
  m_axis_tkeep(1) <= \<const0>\;
  m_axis_tkeep(0) <= \<const0>\;
  m_axis_tlast <= \^s_axis_tlast\;
  m_axis_tstrb(31) <= \<const0>\;
  m_axis_tstrb(30) <= \<const0>\;
  m_axis_tstrb(29) <= \<const0>\;
  m_axis_tstrb(28) <= \<const0>\;
  m_axis_tstrb(27) <= \<const0>\;
  m_axis_tstrb(26) <= \<const0>\;
  m_axis_tstrb(25) <= \<const0>\;
  m_axis_tstrb(24) <= \<const0>\;
  m_axis_tstrb(23) <= \<const0>\;
  m_axis_tstrb(22) <= \<const0>\;
  m_axis_tstrb(21) <= \<const0>\;
  m_axis_tstrb(20) <= \<const0>\;
  m_axis_tstrb(19) <= \<const0>\;
  m_axis_tstrb(18) <= \<const0>\;
  m_axis_tstrb(17) <= \<const0>\;
  m_axis_tstrb(16) <= \<const0>\;
  m_axis_tstrb(15) <= \<const0>\;
  m_axis_tstrb(14) <= \<const0>\;
  m_axis_tstrb(13) <= \<const0>\;
  m_axis_tstrb(12) <= \<const0>\;
  m_axis_tstrb(11) <= \<const0>\;
  m_axis_tstrb(10) <= \<const0>\;
  m_axis_tstrb(9) <= \<const0>\;
  m_axis_tstrb(8) <= \<const0>\;
  m_axis_tstrb(7) <= \<const0>\;
  m_axis_tstrb(6) <= \<const0>\;
  m_axis_tstrb(5) <= \<const0>\;
  m_axis_tstrb(4) <= \<const0>\;
  m_axis_tstrb(3) <= \<const0>\;
  m_axis_tstrb(2) <= \<const0>\;
  m_axis_tstrb(1) <= \<const0>\;
  m_axis_tstrb(0) <= \<const0>\;
  m_axis_tuser(0) <= \<const0>\;
  m_axis_tvalid <= \^s_axis_tvalid\;
  s_axis_tready <= \^m_axis_tready\;
  sparse_tkeep_removed <= \<const0>\;
  transfer_dropped <= \<const0>\;
GND: unisim.vcomponents.GND
     port map (
      G => \<const0>\
    );
end STRUCTURE;
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
library UNISIM;
use UNISIM.VCOMPONENTS.ALL;
entity decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  port (
    aclk : in STD_LOGIC;
    aresetn : in STD_LOGIC;
    s_axis_tvalid : in STD_LOGIC;
    s_axis_tready : out STD_LOGIC;
    s_axis_tdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axis_tlast : in STD_LOGIC;
    m_axis_tvalid : out STD_LOGIC;
    m_axis_tready : in STD_LOGIC;
    m_axis_tdata : out STD_LOGIC_VECTOR ( 255 downto 0 );
    m_axis_tlast : out STD_LOGIC
  );
  attribute NotValidForBitStream : boolean;
  attribute NotValidForBitStream of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is true;
  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "work_pls_axis_subset_converter_0,top_work_pls_axis_subset_converter_0,{}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "yes";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "top_work_pls_axis_subset_converter_0,Vivado 2024.1";
end decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix;

architecture STRUCTURE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  signal \<const0>\ : STD_LOGIC;
  signal \^m_axis_tdata\ : STD_LOGIC_VECTOR ( 31 downto 0 );
  signal NLW_inst_sparse_tkeep_removed_UNCONNECTED : STD_LOGIC;
  signal NLW_inst_transfer_dropped_UNCONNECTED : STD_LOGIC;
  signal NLW_inst_m_axis_tdata_UNCONNECTED : STD_LOGIC_VECTOR ( 255 downto 32 );
  signal NLW_inst_m_axis_tdest_UNCONNECTED : STD_LOGIC_VECTOR ( 0 to 0 );
  signal NLW_inst_m_axis_tid_UNCONNECTED : STD_LOGIC_VECTOR ( 0 to 0 );
  signal NLW_inst_m_axis_tkeep_UNCONNECTED : STD_LOGIC_VECTOR ( 31 downto 0 );
  signal NLW_inst_m_axis_tstrb_UNCONNECTED : STD_LOGIC_VECTOR ( 31 downto 0 );
  signal NLW_inst_m_axis_tuser_UNCONNECTED : STD_LOGIC_VECTOR ( 0 to 0 );
  attribute C_DEFAULT_TLAST : integer;
  attribute C_DEFAULT_TLAST of inst : label is 0;
  attribute C_FAMILY : string;
  attribute C_FAMILY of inst : label is "zynquplus";
  attribute C_M_AXIS_SIGNAL_SET : integer;
  attribute C_M_AXIS_SIGNAL_SET of inst : label is 19;
  attribute C_M_AXIS_TDATA_WIDTH : integer;
  attribute C_M_AXIS_TDATA_WIDTH of inst : label is 256;
  attribute C_M_AXIS_TDEST_WIDTH : integer;
  attribute C_M_AXIS_TDEST_WIDTH of inst : label is 1;
  attribute C_M_AXIS_TID_WIDTH : integer;
  attribute C_M_AXIS_TID_WIDTH of inst : label is 1;
  attribute C_M_AXIS_TUSER_WIDTH : integer;
  attribute C_M_AXIS_TUSER_WIDTH of inst : label is 1;
  attribute C_S_AXIS_SIGNAL_SET : integer;
  attribute C_S_AXIS_SIGNAL_SET of inst : label is 19;
  attribute C_S_AXIS_TDATA_WIDTH : integer;
  attribute C_S_AXIS_TDATA_WIDTH of inst : label is 32;
  attribute C_S_AXIS_TDEST_WIDTH : integer;
  attribute C_S_AXIS_TDEST_WIDTH of inst : label is 1;
  attribute C_S_AXIS_TID_WIDTH : integer;
  attribute C_S_AXIS_TID_WIDTH of inst : label is 1;
  attribute C_S_AXIS_TUSER_WIDTH : integer;
  attribute C_S_AXIS_TUSER_WIDTH of inst : label is 1;
  attribute G_INDX_SS_TDATA : integer;
  attribute G_INDX_SS_TDATA of inst : label is 1;
  attribute G_INDX_SS_TDEST : integer;
  attribute G_INDX_SS_TDEST of inst : label is 6;
  attribute G_INDX_SS_TID : integer;
  attribute G_INDX_SS_TID of inst : label is 5;
  attribute G_INDX_SS_TKEEP : integer;
  attribute G_INDX_SS_TKEEP of inst : label is 3;
  attribute G_INDX_SS_TLAST : integer;
  attribute G_INDX_SS_TLAST of inst : label is 4;
  attribute G_INDX_SS_TREADY : integer;
  attribute G_INDX_SS_TREADY of inst : label is 0;
  attribute G_INDX_SS_TSTRB : integer;
  attribute G_INDX_SS_TSTRB of inst : label is 2;
  attribute G_INDX_SS_TUSER : integer;
  attribute G_INDX_SS_TUSER of inst : label is 7;
  attribute G_MASK_SS_TDATA : integer;
  attribute G_MASK_SS_TDATA of inst : label is 2;
  attribute G_MASK_SS_TDEST : integer;
  attribute G_MASK_SS_TDEST of inst : label is 64;
  attribute G_MASK_SS_TID : integer;
  attribute G_MASK_SS_TID of inst : label is 32;
  attribute G_MASK_SS_TKEEP : integer;
  attribute G_MASK_SS_TKEEP of inst : label is 8;
  attribute G_MASK_SS_TLAST : integer;
  attribute G_MASK_SS_TLAST of inst : label is 16;
  attribute G_MASK_SS_TREADY : integer;
  attribute G_MASK_SS_TREADY of inst : label is 1;
  attribute G_MASK_SS_TSTRB : integer;
  attribute G_MASK_SS_TSTRB of inst : label is 4;
  attribute G_MASK_SS_TUSER : integer;
  attribute G_MASK_SS_TUSER of inst : label is 128;
  attribute G_TASK_SEVERITY_ERR : integer;
  attribute G_TASK_SEVERITY_ERR of inst : label is 2;
  attribute G_TASK_SEVERITY_INFO : integer;
  attribute G_TASK_SEVERITY_INFO of inst : label is 0;
  attribute G_TASK_SEVERITY_WARNING : integer;
  attribute G_TASK_SEVERITY_WARNING of inst : label is 1;
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of aclk : signal is "xilinx.com:signal:clock:1.0 CLKIF CLK";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of aclk : signal is "XIL_INTERFACENAME CLKIF, ASSOCIATED_BUSIF S_AXIS:M_AXIS, ASSOCIATED_RESET aresetn, ASSOCIATED_CLKEN aclken, FREQ_HZ 96968727, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN work_pls_zynq_ultra_ps_e_0_0_pl_clk0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of aresetn : signal is "xilinx.com:signal:reset:1.0 RSTIF RST";
  attribute X_INTERFACE_PARAMETER of aresetn : signal is "XIL_INTERFACENAME RSTIF, POLARITY ACTIVE_LOW, INSERT_VIP 0, TYPE INTERCONNECT";
  attribute X_INTERFACE_INFO of m_axis_tlast : signal is "xilinx.com:interface:axis:1.0 M_AXIS TLAST";
  attribute X_INTERFACE_PARAMETER of m_axis_tlast : signal is "XIL_INTERFACENAME M_AXIS, TDATA_NUM_BYTES 32, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 1, FREQ_HZ 96968727, PHASE 0.0, CLK_DOMAIN work_pls_zynq_ultra_ps_e_0_0_pl_clk0, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axis_tready : signal is "xilinx.com:interface:axis:1.0 M_AXIS TREADY";
  attribute X_INTERFACE_INFO of m_axis_tvalid : signal is "xilinx.com:interface:axis:1.0 M_AXIS TVALID";
  attribute X_INTERFACE_INFO of s_axis_tlast : signal is "xilinx.com:interface:axis:1.0 S_AXIS TLAST";
  attribute X_INTERFACE_PARAMETER of s_axis_tlast : signal is "XIL_INTERFACENAME S_AXIS, TDATA_NUM_BYTES 4, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 1, FREQ_HZ 96968727, PHASE 0.0, CLK_DOMAIN work_pls_zynq_ultra_ps_e_0_0_pl_clk0, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axis_tready : signal is "xilinx.com:interface:axis:1.0 S_AXIS TREADY";
  attribute X_INTERFACE_INFO of s_axis_tvalid : signal is "xilinx.com:interface:axis:1.0 S_AXIS TVALID";
  attribute X_INTERFACE_INFO of m_axis_tdata : signal is "xilinx.com:interface:axis:1.0 M_AXIS TDATA";
  attribute X_INTERFACE_INFO of s_axis_tdata : signal is "xilinx.com:interface:axis:1.0 S_AXIS TDATA";
begin
  m_axis_tdata(255) <= \<const0>\;
  m_axis_tdata(254) <= \<const0>\;
  m_axis_tdata(253) <= \<const0>\;
  m_axis_tdata(252) <= \<const0>\;
  m_axis_tdata(251) <= \<const0>\;
  m_axis_tdata(250) <= \<const0>\;
  m_axis_tdata(249) <= \<const0>\;
  m_axis_tdata(248) <= \<const0>\;
  m_axis_tdata(247) <= \<const0>\;
  m_axis_tdata(246) <= \<const0>\;
  m_axis_tdata(245) <= \<const0>\;
  m_axis_tdata(244) <= \<const0>\;
  m_axis_tdata(243) <= \<const0>\;
  m_axis_tdata(242) <= \<const0>\;
  m_axis_tdata(241) <= \<const0>\;
  m_axis_tdata(240) <= \<const0>\;
  m_axis_tdata(239) <= \<const0>\;
  m_axis_tdata(238) <= \<const0>\;
  m_axis_tdata(237) <= \<const0>\;
  m_axis_tdata(236) <= \<const0>\;
  m_axis_tdata(235) <= \<const0>\;
  m_axis_tdata(234) <= \<const0>\;
  m_axis_tdata(233) <= \<const0>\;
  m_axis_tdata(232) <= \<const0>\;
  m_axis_tdata(231) <= \<const0>\;
  m_axis_tdata(230) <= \<const0>\;
  m_axis_tdata(229) <= \<const0>\;
  m_axis_tdata(228) <= \<const0>\;
  m_axis_tdata(227) <= \<const0>\;
  m_axis_tdata(226) <= \<const0>\;
  m_axis_tdata(225) <= \<const0>\;
  m_axis_tdata(224) <= \<const0>\;
  m_axis_tdata(223) <= \<const0>\;
  m_axis_tdata(222) <= \<const0>\;
  m_axis_tdata(221) <= \<const0>\;
  m_axis_tdata(220) <= \<const0>\;
  m_axis_tdata(219) <= \<const0>\;
  m_axis_tdata(218) <= \<const0>\;
  m_axis_tdata(217) <= \<const0>\;
  m_axis_tdata(216) <= \<const0>\;
  m_axis_tdata(215) <= \<const0>\;
  m_axis_tdata(214) <= \<const0>\;
  m_axis_tdata(213) <= \<const0>\;
  m_axis_tdata(212) <= \<const0>\;
  m_axis_tdata(211) <= \<const0>\;
  m_axis_tdata(210) <= \<const0>\;
  m_axis_tdata(209) <= \<const0>\;
  m_axis_tdata(208) <= \<const0>\;
  m_axis_tdata(207) <= \<const0>\;
  m_axis_tdata(206) <= \<const0>\;
  m_axis_tdata(205) <= \<const0>\;
  m_axis_tdata(204) <= \<const0>\;
  m_axis_tdata(203) <= \<const0>\;
  m_axis_tdata(202) <= \<const0>\;
  m_axis_tdata(201) <= \<const0>\;
  m_axis_tdata(200) <= \<const0>\;
  m_axis_tdata(199) <= \<const0>\;
  m_axis_tdata(198) <= \<const0>\;
  m_axis_tdata(197) <= \<const0>\;
  m_axis_tdata(196) <= \<const0>\;
  m_axis_tdata(195) <= \<const0>\;
  m_axis_tdata(194) <= \<const0>\;
  m_axis_tdata(193) <= \<const0>\;
  m_axis_tdata(192) <= \<const0>\;
  m_axis_tdata(191) <= \<const0>\;
  m_axis_tdata(190) <= \<const0>\;
  m_axis_tdata(189) <= \<const0>\;
  m_axis_tdata(188) <= \<const0>\;
  m_axis_tdata(187) <= \<const0>\;
  m_axis_tdata(186) <= \<const0>\;
  m_axis_tdata(185) <= \<const0>\;
  m_axis_tdata(184) <= \<const0>\;
  m_axis_tdata(183) <= \<const0>\;
  m_axis_tdata(182) <= \<const0>\;
  m_axis_tdata(181) <= \<const0>\;
  m_axis_tdata(180) <= \<const0>\;
  m_axis_tdata(179) <= \<const0>\;
  m_axis_tdata(178) <= \<const0>\;
  m_axis_tdata(177) <= \<const0>\;
  m_axis_tdata(176) <= \<const0>\;
  m_axis_tdata(175) <= \<const0>\;
  m_axis_tdata(174) <= \<const0>\;
  m_axis_tdata(173) <= \<const0>\;
  m_axis_tdata(172) <= \<const0>\;
  m_axis_tdata(171) <= \<const0>\;
  m_axis_tdata(170) <= \<const0>\;
  m_axis_tdata(169) <= \<const0>\;
  m_axis_tdata(168) <= \<const0>\;
  m_axis_tdata(167) <= \<const0>\;
  m_axis_tdata(166) <= \<const0>\;
  m_axis_tdata(165) <= \<const0>\;
  m_axis_tdata(164) <= \<const0>\;
  m_axis_tdata(163) <= \<const0>\;
  m_axis_tdata(162) <= \<const0>\;
  m_axis_tdata(161) <= \<const0>\;
  m_axis_tdata(160) <= \<const0>\;
  m_axis_tdata(159) <= \<const0>\;
  m_axis_tdata(158) <= \<const0>\;
  m_axis_tdata(157) <= \<const0>\;
  m_axis_tdata(156) <= \<const0>\;
  m_axis_tdata(155) <= \<const0>\;
  m_axis_tdata(154) <= \<const0>\;
  m_axis_tdata(153) <= \<const0>\;
  m_axis_tdata(152) <= \<const0>\;
  m_axis_tdata(151) <= \<const0>\;
  m_axis_tdata(150) <= \<const0>\;
  m_axis_tdata(149) <= \<const0>\;
  m_axis_tdata(148) <= \<const0>\;
  m_axis_tdata(147) <= \<const0>\;
  m_axis_tdata(146) <= \<const0>\;
  m_axis_tdata(145) <= \<const0>\;
  m_axis_tdata(144) <= \<const0>\;
  m_axis_tdata(143) <= \<const0>\;
  m_axis_tdata(142) <= \<const0>\;
  m_axis_tdata(141) <= \<const0>\;
  m_axis_tdata(140) <= \<const0>\;
  m_axis_tdata(139) <= \<const0>\;
  m_axis_tdata(138) <= \<const0>\;
  m_axis_tdata(137) <= \<const0>\;
  m_axis_tdata(136) <= \<const0>\;
  m_axis_tdata(135) <= \<const0>\;
  m_axis_tdata(134) <= \<const0>\;
  m_axis_tdata(133) <= \<const0>\;
  m_axis_tdata(132) <= \<const0>\;
  m_axis_tdata(131) <= \<const0>\;
  m_axis_tdata(130) <= \<const0>\;
  m_axis_tdata(129) <= \<const0>\;
  m_axis_tdata(128) <= \<const0>\;
  m_axis_tdata(127) <= \<const0>\;
  m_axis_tdata(126) <= \<const0>\;
  m_axis_tdata(125) <= \<const0>\;
  m_axis_tdata(124) <= \<const0>\;
  m_axis_tdata(123) <= \<const0>\;
  m_axis_tdata(122) <= \<const0>\;
  m_axis_tdata(121) <= \<const0>\;
  m_axis_tdata(120) <= \<const0>\;
  m_axis_tdata(119) <= \<const0>\;
  m_axis_tdata(118) <= \<const0>\;
  m_axis_tdata(117) <= \<const0>\;
  m_axis_tdata(116) <= \<const0>\;
  m_axis_tdata(115) <= \<const0>\;
  m_axis_tdata(114) <= \<const0>\;
  m_axis_tdata(113) <= \<const0>\;
  m_axis_tdata(112) <= \<const0>\;
  m_axis_tdata(111) <= \<const0>\;
  m_axis_tdata(110) <= \<const0>\;
  m_axis_tdata(109) <= \<const0>\;
  m_axis_tdata(108) <= \<const0>\;
  m_axis_tdata(107) <= \<const0>\;
  m_axis_tdata(106) <= \<const0>\;
  m_axis_tdata(105) <= \<const0>\;
  m_axis_tdata(104) <= \<const0>\;
  m_axis_tdata(103) <= \<const0>\;
  m_axis_tdata(102) <= \<const0>\;
  m_axis_tdata(101) <= \<const0>\;
  m_axis_tdata(100) <= \<const0>\;
  m_axis_tdata(99) <= \<const0>\;
  m_axis_tdata(98) <= \<const0>\;
  m_axis_tdata(97) <= \<const0>\;
  m_axis_tdata(96) <= \<const0>\;
  m_axis_tdata(95) <= \<const0>\;
  m_axis_tdata(94) <= \<const0>\;
  m_axis_tdata(93) <= \<const0>\;
  m_axis_tdata(92) <= \<const0>\;
  m_axis_tdata(91) <= \<const0>\;
  m_axis_tdata(90) <= \<const0>\;
  m_axis_tdata(89) <= \<const0>\;
  m_axis_tdata(88) <= \<const0>\;
  m_axis_tdata(87) <= \<const0>\;
  m_axis_tdata(86) <= \<const0>\;
  m_axis_tdata(85) <= \<const0>\;
  m_axis_tdata(84) <= \<const0>\;
  m_axis_tdata(83) <= \<const0>\;
  m_axis_tdata(82) <= \<const0>\;
  m_axis_tdata(81) <= \<const0>\;
  m_axis_tdata(80) <= \<const0>\;
  m_axis_tdata(79) <= \<const0>\;
  m_axis_tdata(78) <= \<const0>\;
  m_axis_tdata(77) <= \<const0>\;
  m_axis_tdata(76) <= \<const0>\;
  m_axis_tdata(75) <= \<const0>\;
  m_axis_tdata(74) <= \<const0>\;
  m_axis_tdata(73) <= \<const0>\;
  m_axis_tdata(72) <= \<const0>\;
  m_axis_tdata(71) <= \<const0>\;
  m_axis_tdata(70) <= \<const0>\;
  m_axis_tdata(69) <= \<const0>\;
  m_axis_tdata(68) <= \<const0>\;
  m_axis_tdata(67) <= \<const0>\;
  m_axis_tdata(66) <= \<const0>\;
  m_axis_tdata(65) <= \<const0>\;
  m_axis_tdata(64) <= \<const0>\;
  m_axis_tdata(63) <= \<const0>\;
  m_axis_tdata(62) <= \<const0>\;
  m_axis_tdata(61) <= \<const0>\;
  m_axis_tdata(60) <= \<const0>\;
  m_axis_tdata(59) <= \<const0>\;
  m_axis_tdata(58) <= \<const0>\;
  m_axis_tdata(57) <= \<const0>\;
  m_axis_tdata(56) <= \<const0>\;
  m_axis_tdata(55) <= \<const0>\;
  m_axis_tdata(54) <= \<const0>\;
  m_axis_tdata(53) <= \<const0>\;
  m_axis_tdata(52) <= \<const0>\;
  m_axis_tdata(51) <= \<const0>\;
  m_axis_tdata(50) <= \<const0>\;
  m_axis_tdata(49) <= \<const0>\;
  m_axis_tdata(48) <= \<const0>\;
  m_axis_tdata(47) <= \<const0>\;
  m_axis_tdata(46) <= \<const0>\;
  m_axis_tdata(45) <= \<const0>\;
  m_axis_tdata(44) <= \<const0>\;
  m_axis_tdata(43) <= \<const0>\;
  m_axis_tdata(42) <= \<const0>\;
  m_axis_tdata(41) <= \<const0>\;
  m_axis_tdata(40) <= \<const0>\;
  m_axis_tdata(39) <= \<const0>\;
  m_axis_tdata(38) <= \<const0>\;
  m_axis_tdata(37) <= \<const0>\;
  m_axis_tdata(36) <= \<const0>\;
  m_axis_tdata(35) <= \<const0>\;
  m_axis_tdata(34) <= \<const0>\;
  m_axis_tdata(33) <= \<const0>\;
  m_axis_tdata(32) <= \<const0>\;
  m_axis_tdata(31 downto 0) <= \^m_axis_tdata\(31 downto 0);
GND: unisim.vcomponents.GND
     port map (
      G => \<const0>\
    );
inst: entity work.decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_top_work_pls_axis_subset_converter_0
     port map (
      aclk => '0',
      aclken => '1',
      aresetn => '0',
      m_axis_tdata(255 downto 32) => NLW_inst_m_axis_tdata_UNCONNECTED(255 downto 32),
      m_axis_tdata(31 downto 0) => \^m_axis_tdata\(31 downto 0),
      m_axis_tdest(0) => NLW_inst_m_axis_tdest_UNCONNECTED(0),
      m_axis_tid(0) => NLW_inst_m_axis_tid_UNCONNECTED(0),
      m_axis_tkeep(31 downto 0) => NLW_inst_m_axis_tkeep_UNCONNECTED(31 downto 0),
      m_axis_tlast => m_axis_tlast,
      m_axis_tready => m_axis_tready,
      m_axis_tstrb(31 downto 0) => NLW_inst_m_axis_tstrb_UNCONNECTED(31 downto 0),
      m_axis_tuser(0) => NLW_inst_m_axis_tuser_UNCONNECTED(0),
      m_axis_tvalid => m_axis_tvalid,
      s_axis_tdata(31 downto 0) => s_axis_tdata(31 downto 0),
      s_axis_tdest(0) => '0',
      s_axis_tid(0) => '0',
      s_axis_tkeep(3 downto 0) => B"1111",
      s_axis_tlast => s_axis_tlast,
      s_axis_tready => s_axis_tready,
      s_axis_tstrb(3 downto 0) => B"1111",
      s_axis_tuser(0) => '0',
      s_axis_tvalid => s_axis_tvalid,
      sparse_tkeep_removed => NLW_inst_sparse_tkeep_removed_UNCONNECTED,
      transfer_dropped => NLW_inst_transfer_dropped_UNCONNECTED
    );
end STRUCTURE;
