# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.srcs/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/helloworld_axi_smc_5.xci
# IP: The module: 'helloworld_axi_smc_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/bd_0/bd_6589.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/bd_0/ip/ip_0/bd_6589_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/bd_0/ip/ip_1/bd_6589_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/bd_0/ip/ip_2/bd_6589_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/bd_0/ip/ip_3/bd_6589_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/bd_0/ip/ip_4/bd_6589_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/bd_0/ip/ip_5/bd_6589_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/bd_0/ip/ip_6/bd_6589_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/bd_0/ip/ip_7/bd_6589_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/bd_0/ip/ip_8/bd_6589_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/bd_0/ip/ip_9/bd_6589_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/bd_0/ip/ip_1/bd_6589_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/bd_0/ip/ip_1/bd_6589_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/bd_0/ip/ip_5/bd_6589_s00a2s_0_ooc.xdc

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/bd_0/ip/ip_6/bd_6589_sarn_0_ooc.xdc

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/bd_0/ip/ip_6/bd_6589_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/bd_0/ip/ip_7/bd_6589_srn_0_ooc.xdc

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/bd_0/ip/ip_7/bd_6589_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/bd_0/ip/ip_8/bd_6589_m00s2a_0_ooc.xdc

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'helloworld_axi_smc_5'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'helloworld_axi_smc_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.srcs/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/helloworld_axi_smc_5.xci
# IP: The module: 'helloworld_axi_smc_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/bd_0/bd_6589.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/bd_0/ip/ip_0/bd_6589_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/bd_0/ip/ip_1/bd_6589_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/bd_0/ip/ip_2/bd_6589_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/bd_0/ip/ip_3/bd_6589_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/bd_0/ip/ip_4/bd_6589_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/bd_0/ip/ip_5/bd_6589_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/bd_0/ip/ip_6/bd_6589_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/bd_0/ip/ip_7/bd_6589_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/bd_0/ip/ip_8/bd_6589_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/bd_0/ip/ip_9/bd_6589_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/bd_0/ip/ip_1/bd_6589_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/bd_0/ip/ip_1/bd_6589_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/bd_0/ip/ip_5/bd_6589_s00a2s_0_ooc.xdc

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/bd_0/ip/ip_6/bd_6589_sarn_0_ooc.xdc

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/bd_0/ip/ip_6/bd_6589_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/bd_0/ip/ip_7/bd_6589_srn_0_ooc.xdc

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/bd_0/ip/ip_7/bd_6589_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/bd_0/ip/ip_8/bd_6589_m00s2a_0_ooc.xdc

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'helloworld_axi_smc_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/vivado_project/vivado_project.gen/sources_1/bd/helloworld/ip/helloworld_axi_smc_5/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'helloworld_axi_smc_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
