# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/PYNQ_Receiver/PYNQ_Receiver.srcs/sources_1/bd/work_pls/ip/work_pls_zynq_ultra_ps_e_0_0/work_pls_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'work_pls_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/PYNQ_Receiver/PYNQ_Receiver.gen/sources_1/bd/work_pls/ip/work_pls_zynq_ultra_ps_e_0_0/work_pls_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'work_pls_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/PYNQ_Receiver/PYNQ_Receiver.gen/sources_1/bd/work_pls/ip/work_pls_zynq_ultra_ps_e_0_0/work_pls_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'work_pls_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/PYNQ_Receiver/PYNQ_Receiver.srcs/sources_1/bd/work_pls/ip/work_pls_zynq_ultra_ps_e_0_0/work_pls_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'work_pls_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/PYNQ_Receiver/PYNQ_Receiver.gen/sources_1/bd/work_pls/ip/work_pls_zynq_ultra_ps_e_0_0/work_pls_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'work_pls_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/clb20123/Documents/FO-RFSoC-4YP/2x2_files/PYNQ_Receiver/PYNQ_Receiver.gen/sources_1/bd/work_pls/ip/work_pls_zynq_ultra_ps_e_0_0/work_pls_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'work_pls_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
